rewriting some tests using new limsmock
Clinical-Genomics/cg_lims pull request #22
Opened 2021-01-20 13:42 UTC by mayabrandi

### This PR rewrites some tests using the new limsmock package
- 

**How to test**:
- [ ] clone and run `pytest tests/get/test_artifacts.py`

### Review:
- [ ] Code approved by
- [ ] Tests executed by
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [x] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2021-01-25 15:26 UTC, Mropat commented on tests/EPPs/test_make_kapa_csv.py
> +    lims = Lims("http://127.0.0.1:8000", 'dummy', 'dummy')
can this be moved into a fixture? You will be using this IP:port multiple times!

2021-01-25 15:27 UTC, Mropat commented on tests/EPPs/test_make_kapa_csv.py
> +    curent_step_artifacts = [Artifact(lims, id='2-1155129'), Artifact(lims, id='2-1155130')]
could the step artifacts also be predefined in fixture?

2021-01-25 15:28 UTC, Mropat commented on tests/EPPs/test_make_kapa_csv.py
> +    lims = Lims("http://127.0.0.1:8000", 'dummy', 'dummy')
Also for the amount_step variable, its repeated a bunch in tests!

2021-01-28 06:47 UTC, mayabrandi commented on tests/EPPs/test_make_kapa_csv.py
> +    curent_step_artifacts = [Artifact(lims, id='2-1155129'), Artifact(lims, id='2-1155130')]
Im not sure. Maybe we can talk about it and conclude together?

2021-01-28 08:30 UTC, moonso requested changes
Great job!

2021-01-28 08:30 UTC, moonso commented on tests/EPPs/test_make_kapa_csv.py
> +    curent_step_artifacts = [Artifact(lims, id='2-1155124'), Artifact(lims, id='2-1155125')]
Fixture from previous test can be reused here

2021-01-28 08:30 UTC, moonso commented on tests/EPPs/test_make_kapa_csv.py
> +        server_make_kapa_csv_missing_udfs, kapa_library_preparation_file_missing_udf, lims):
Adding type hints makes also the tests much easier to read!
I think my type hints suggestions are wrong but just exemplifying 

```suggestion
        server_make_kapa_csv_missing_udfs: str, kapa_library_preparation_file_missing_udf: str, lims: Lims):
```

2021-01-28 08:30 UTC, moonso commented on tests/EPPs/test_twist_qc_amount.py
> +    a1 = Artifact(lims, id='1')
Suggest to split these into individual tests that can be called something like
`test_qc_fails_when_concentration_300`

2021-01-28 08:30 UTC, moonso commented on tests/EPPs/test_twist_qc_amount.py
> +    a1 = Artifact(lims, id='1')
It is easier to read and understand why tests fails if one test only test one thing

2021-01-28 08:30 UTC, moonso commented on tests/conftest.py
> +def server_flat_tests():
Could we add a doc string? I can not figure out what this is used for...
Nothing is returned so it is kind of hard to follow

2021-01-28 08:30 UTC, moonso commented on tests/conftest.py
> +def lims():
```suggestion
def lims() -> Lims:
```

2021-01-28 08:30 UTC, moonso commented on tests/conftest.py
> +    return lims
```suggestion
    return Lims(f"http://{HOST}:{PORT}", 'dummy', 'dummy')
```

2021-01-28 08:30 UTC, moonso commented on tests/conftest.py
> +def config():
Suggest to always use Path objects when working with anything on the file system
```suggestion
def config() -> Path:
```

2021-01-28 08:30 UTC, moonso commented on tests/conftest.py
> +    return "tests/fixtures/config.yaml"
```suggestion
    return Path("tests/fixtures/config.yaml")
```

2021-01-28 08:30 UTC, moonso commented on tests/fixtures/config.yaml
> +CG_URL: https://something
```suggestion
CG_URL: https://something

```

2021-01-28 08:30 UTC, moonso commented on tests/fixtures/flat_tests/artifacts/4.xml
> +<art:artifact xmlns:udf="http://genologics.com/ri/userdefined" xmlns:file="http://genologics.com/ri/file" xmlns:art="http://genologics.com/ri/artifact" uri="http://127.0.0.1:8000/api/v2/artifacts/2-1
It wold be nice if these had some name that describes more what they are so one can understand why they are different

2021-01-28 10:19 UTC, mayabrandi commented on tests/EPPs/test_twist_qc_amount.py
> +    a1 = Artifact(lims, id='1')
Good point

2021-01-28 10:33 UTC, mayabrandi commented on tests/EPPs/test_make_kapa_csv.py
> +    curent_step_artifacts = [Artifact(lims, id='2-1155129'), Artifact(lims, id='2-1155130')]
Don't agree on these once. Ill make fixures for artifacts that can and will be used several times. Here i think its better to create the artifact within the test

2021-01-28 10:34 UTC, mayabrandi commented on tests/conftest.py
> +def server_flat_tests():
Absolutely. 👍

2021-01-28 12:22 UTC, mayabrandi commented
Thanks for great feedback @moonso @Mropat! I'm done now. You want to approve? Or you want me to do additional changes?

2021-01-29 13:03 UTC, moonso approved these changes
👍 Did it not work to have server in a fixture?

2021-02-01 07:11 UTC, Mropat commented
Did not make sense to have server as fixture, I think. It returns nothing and has no type, and fixtures cannot be dynamic, so in the end one has to make multiple server fixtures (but server function can spin up server with any given file path as argument)

2021-02-01 08:28 UTC, mayabrandi commented
I made server fixtures fo the servers that will be reused several times but not for the specific once used on or two times. @moonso

2021-02-01 09:05 UTC, merged