Removes_valid_input_amounts
Clinical-Genomics/cg_lims pull request #280
Opened 2022-05-09 07:59 UTC by cesve

### Added

### Changed
Removed valid input amounts.

### Fixed

**Steps to consider while deploying**
- Configuration changes:
- Documentation updates:
- Inform users by email:

### Review:
- [ ] Code approved by
- [ ] Tests executed on stage by:  (Document the test done with screen shots and description.)
- [ ] "Merge and deploy" approved by

This [version](https://semver.org/) is a:
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [x] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

2022-05-17 08:24 UTC, RasmusBurge-CG commented
Removed all test that checks VALID_AMOUNTS_NEEDED

2022-05-17 08:26 UTC, RasmusBurge-CG commented
<img width="2098" alt="Screenshot 2022-05-17 at 10 25 37" src="https://user-images.githubusercontent.com/80392398/168765844-19904837-28a2-4cf7-b974-56fe8b593eb1.png">

2022-05-17 14:07 UTC, RasmusBurge-CG commented
Could you test this? @cesve

2022-05-17 17:21 UTC, cesve commented
Tested on stage 22-05-17:

Script worked when different values of "Amount needed (ng)":

<img width="1406" alt="Screenshot 2022-05-17 at 19 18 26" src="https://user-images.githubusercontent.com/37171914/168872952-bafa38ab-7bf7-4ed7-94bb-2961f7357877.png">

The calculations were correct:
<img width="1175" alt="Screenshot 2022-05-17 at 19 18 34" src="https://user-images.githubusercontent.com/37171914/168872927-b20c73ea-0729-4c37-8962-ebf06bd1db8a.png">

2022-05-17 17:22 UTC, cesve commented
Tested on stage 22-05-17:

The script worked well when different values were set for UDF "Amount needed (ng)".
<img width="1175" alt="Screenshot 2022-05-17 at 19 18 34" src="https://user-images.githubusercontent.com/37171914/168873319-542798e0-22cc-49ce-80a1-29dd76f73a79.png">

2022-05-17 17:56 UTC, cesve commented
@RasmusBurge-CG it looks really good!

2022-05-18 10:23 UTC, RasmusBurge-CG commented
@cesve are we ready for review? :)

2022-05-18 12:48 UTC, cesve commented
Yes, @Karl-Svard when you have time it would be great if you can review :)

2022-05-20 06:04 UTC, Karl-Svard requested changes

2022-05-20 06:04 UTC, Karl-Svard commented on cg_lims/EPPs/udf/calculate/calculate_water_volume_rna.py
> -            )
Keep this check if we still require the amount_needed udf to exist. Just modify it to work similar to the one that checks the concentration.

2022-05-20 06:04 UTC, Karl-Svard commented on tests/EPPs/udf/calculate/test_calculate_water_volume_rna.py
> -    )
Keep this pytest as it will still be relevant.

2022-05-20 06:04 UTC, Karl-Svard commented on tests/EPPs/udf/calculate/test_calculate_water_volume_rna.py
> -    )
Keep this pytest as it will still be relevant.

2022-05-30 11:48 UTC, cesve commented on cg_lims/EPPs/udf/calculate/calculate_water_volume_rna.py
> -            )
ok

2022-05-30 11:55 UTC, cesve commented on tests/EPPs/udf/calculate/test_calculate_water_volume_rna.py
```suggestion

@pytest.mark.parametrize(
    "concentration",
    [
        100,
    ],
)
def test_calculate_water_volume_rna_amount_needed_missing(
    concentration, artifact_1: Artifact
):
    # GIVEN a list of artifacts with one artifact having no 'Amount Needed (ng)' udf
    artifact_1.udf["Concentration"] = concentration
    del artifact_1.udf["Amount needed (ng)"]
    artifacts = [artifact_1]

    # WHEN calculating sample and water volumes for all samples
    with pytest.raises(InvalidValueError) as error_message:
        calculate_sample_and_water_volumes(artifacts)

    # THEN the InvalidValueError exception should be raised
    assert (
        f"'Amount needed (ng)' missing or incorrect for one or more samples."
        in error_message.value.message
```

2022-05-31 08:46 UTC, RasmusBurge-CG commented
@Karl-Svard redo för review när du har tid :)

2022-05-31 08:53 UTC, Karl-Svard approved these changes
Nice! Litet förslag som gör koden snyggare bara :)

2022-05-31 08:53 UTC, Karl-Svard commented on tests/EPPs/udf/calculate/test_calculate_water_volume_rna.py
> +        in error_message.value.message)
```suggestion
        in error_message.value.message
    )
```

2022-05-31 08:54 UTC, RasmusBurge-CG commented
<img width="799" alt="Screenshot 2022-05-31 at 10 52 52" src="https://user-images.githubusercontent.com/80392398/171133869-a917ffc1-92ab-420e-b29c-25e23319a90a.png">

Test error messages for when 'Amount needed (ng)' is none.

2022-05-31 10:28 UTC, cesve commented
Should I re-do the test I did 2 weeks ago?

2022-05-31 10:41 UTC, RasmusBurge-CG commented
> Should I re-do the test I did 2 weeks ago? @RasmusBurge-CG

Yea, lets do that. It should not be any difference but you never know. :)

2022-06-01 13:21 UTC, cesve commented
@RasmusBurge-CG test is done successfully! The updated script is ready for production.

2022-06-02 06:17 UTC, merged